declare module 'react-transition-group';
declare module 'react-copy-to-clipboard';
declare module 'prismjs';
declare module 'js-cookie';
declare module 'zustand';
declare module 'nprogress';
declare module 'uuid';
declare module 'lodash';
declare module 'react-katex';